package fr.excilys.enumerations;

public enum MenuModifSwitch {

	DEFAULT, MODIF_NAME_ORDI, MODIF_INTRODUCED_ORDI, MODIF_DISCONTINUED_ORDI, MODIF_ID__ORDI_ENTREPRISE, ENVOYER_MODIFICATION, QUITTER;
}
